"""Effusive MATLAB engine worker subprocess.

Runs as a subprocess of the napari viewer process so that MATLAB's bundled Qt libraries
(loaded via LD_LIBRARY_PATH) never enter the napari/Qt process.

Startup sequence:
  1. Set Linux GUI and library environment variables for MATLAB.
  2. Import and start matlab.engine.
  3. Add EchoFrame and Effusive paths to the MATLAB session.
  4. Write initial acquisition parameters to the MATLAB base workspace.
  5. Call `cf_setup`: synchronous, fast; writes nz/nx to the metadata segment.
  6. Call `VSX`: blocks for the duration of the acquisition session.
  7. Quit the engine and exit.

Runtime control (freeze, vsExit, SVD threshold, ...) flows through the command
shared-memory segment, which `processRuntimeControl` reads every frame. No workspace
writes are sent after `VSX` is called.

Usage (from the viewer / `subprocess.Popen`):

```bash
python matlab_worker.py '<JSON config string>'
```

JSON config keys (all optional, defaults shown):
- `matlabRoot`: Path to MATLAB installation root. Required: `MATLAB_ROOT` env var
  or explicit config.
- `matlabStartupOptions`: Extra command-line options passed to MATLAB engine startup.
  Default: empty.
- `echoFrameMexRoot`: Directory containing EchoFrame runtime MEX files
  (`echoframe_mex.*`). Required: `ECHOFRAME_MEX_ROOT` env var or explicit
  config.
- `effusiveRoot`: Path to Effusive repo root. Default: auto-detected (2 levels
  above this file).
- `vantageRoot`: Path to Vantage (Verasonics) installation. Required:
  `VERASONICS_VPF_ROOT` env var or explicit config.
- `probeName`: Ultrasound probe model name. Default: 'L22-14v'.
- `transmitFrequency`: Transmit frequency [MHz]. Default: probe-specific.
- `storagePath`: Root directory for per-session output folders. Default:
  `/tmp/effusive`.
- `sessionId`: Session identifier shared across the viewer log, VSX MAT file,
  and MATLAB session folder. Default: generated by the viewer.
- `bidsSubject`: Default BIDS subject label without the `sub-` prefix.
- `bidsSession`: Default BIDS session label without the `ses-` prefix.
- `bidsTask`: Default BIDS task label without the `task-` prefix.
- `bidsAcq`: Default BIDS acquisition label without the `acq-` prefix.
- `bidsProc`: Default BIDS processing label without the `proc-` prefix.
- `bidsRun`: Default run value for recordings.
- `voltage`: Acquisition voltage (V). Default: 1.6.
- `transmitAperturePercentage`: Initial TX aperture [%]. Default: 100.
- `receiveAperturePercentage`: Initial RX aperture [%]. Default: 100.
- `txrxFrameRate`: Acquisition frame rate [Hz]. Default: probe-specific.
- `transmitPulseLength`: Pulse length [half cycles]. Default: 3.
- `nTransmissions`: Number of compounded transmit angles. Default: probe-specific.
- `nRepeats`: Ensemble size. Default: probe-specific.
- `planewaveOpeningAngle`: Total steering angle range [deg]. Default: probe-specific.
- `desiredEndDepthMm`: Imaging depth [mm]. Default: 12.
- `speedOfSound`: Speed of sound [m/s]. Default: 1510.
- `beamformerType`: EchoFrame beamformer, `Fourier` or `DAS`. Default: `Fourier`.
- `dasFNumberAuto`: Compute DAS receive f-number from probe metadata. Default: false.
- `dasFNumber`: Manual DAS receive f-number. Default: 0.71.
- `tgcGain`: Initial TGC gain. Default: 900.
- `tgcControlPoints`: Initial Verasonics TGC control points. Default: eight points at
  `tgcGain`.
- `simulateMode`: 0 = real hardware, 1 = Media simulation, 2 = replay preloaded
  `RcvData`. Default: derived from `system.simulate_mode` in `default_config.toml`.
- `rcvDataMatFile`: Path to a MAT file containing `RcvData` for
  `simulateMode=2`. Default: empty.
"""

from __future__ import annotations

import json
import os
import struct
import sys
import warnings
from multiprocessing import resource_tracker, shared_memory
from pathlib import Path

from effusive import bids
from effusive import config as cf_config
from effusive.shared_memory import (
    META_FORMAT,
    SHARED_MEMORY_BMODE_NAME,
    SHARED_MEMORY_CMD_NAME,
    SHARED_MEMORY_META_NAME,
    SHARED_MEMORY_PDI_NAME,
    SHARED_MEMORY_RF_NAME,
    SHARED_MEMORY_ACK_NAME,
    SHARED_MEMORY_STACK_NAME,
)

# Suppress harmless resource_tracker warnings about already-cleaned shared memory.
warnings.filterwarnings(
    "ignore",
    message="resource_tracker: There appear to be .* leaked shared_memory objects",
    category=UserWarning,
)
warnings.filterwarnings(
    "ignore",
    message="resource_tracker: .*No such file or directory",
    category=UserWarning,
)


# Ensure the effusive package is importable when this script runs as a
# subprocess with a bare Python interpreter.
_SRC_DIR = Path(__file__).resolve().parent.parent  # src/
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))
_EFFUSIVE_ROOT = _SRC_DIR.parent

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------


def _defaults_from_config(probe_name: str | None = None) -> dict:
    """Build the worker default config from the shipped default_config.toml.

    Parameters
    ----------
    probe_name : str, optional
        Probe model name to use for probe-specific defaults. Falls back to
        the config's default probe when omitted or unrecognised.

    Returns
    -------
    dict
        Flat worker-config dict with all acquisition parameters populated from
        the config file. System paths are sourced from environment variables
        because they are machine-specific, not acquisition parameters.
    """
    default_cfg = cf_config.load_default_config()
    probe = default_cfg.get_probe(probe_name or default_cfg.system.default_probe)
    acq = default_cfg.acquisition
    stack = default_cfg.stack
    return {
        "matlabRoot": os.environ.get("MATLAB_ROOT"),
        "matlabStartupOptions": "",
        "echoFrameMexRoot": os.environ.get("ECHOFRAME_MEX_ROOT"),
        "effusiveRoot": str(_EFFUSIVE_ROOT),
        "vantageRoot": os.environ.get("VERASONICS_VPF_ROOT"),
        "probeName": probe_name or default_cfg.system.default_probe,
        "transmitFrequency": probe.transmit_frequency_mhz,
        "storagePath": default_cfg.system.storage_path,
        "sessionId": "",
        "bidsSubject": default_cfg.bids.subject,
        "bidsSession": default_cfg.bids.session,
        "bidsTask": default_cfg.bids.task,
        "bidsAcq": default_cfg.bids.acq,
        "bidsProc": default_cfg.bids.proc,
        "bidsRun": int(default_cfg.bids.run),
        "voltage": acq.voltage_v,
        "transmitAperturePercentage": acq.tx_aperture_percent,
        "receiveAperturePercentage": acq.rx_aperture_percent,
        "txrxFrameRate": probe.txrx_frame_rate_hz,
        "transmitPulseLength": default_cfg.sequence.transmit_pulse_length,
        "nTransmissions": probe.n_transmissions,
        "nRepeats": probe.n_repeats,
        "planewaveOpeningAngle": probe.planewave_opening_angle_deg,
        "desiredEndDepthMm": default_cfg.sequence.imaging_depth_mm,
        "speedOfSound": default_cfg.sequence.speed_of_sound_m_s,
        "beamformerType": default_cfg.system.beamformer,
        "dasFNumberAuto": default_cfg.system.das_f_number_auto,
        "dasFNumber": default_cfg.system.das_f_number,
        "tgcGain": acq.tgc_control_points[0],
        "tgcControlPoints": list(acq.tgc_control_points),
        "stackMotorMinMm": stack.motor_min_mm,
        "stackMotorMaxMm": stack.motor_max_mm,
        "simulateMode": 1 if default_cfg.system.simulate_mode else 0,
        "rcvDataMatFile": "",
    }


def _safe_unregister_shared_memory(name: str) -> None:
    """Best-effort unregister from multiprocessing resource tracker.

    Some Python builds used in our MATLAB environment lack low-level modules
    needed by `resource_tracker.unregister` internals (for example
    `_posixsubprocess`). In that case shared memory is still usable; only the
    unregister call fails. Swallow those errors to avoid false-negative logs.
    """
    try:
        resource_tracker.unregister(name, "shared_memory")
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main(cfg: dict) -> None:
    """Run the MATLAB engine worker subprocess.

    Parameters
    ----------
    cfg : dict
        Configuration dictionary containing paths and acquisition parameters.
        Required keys: 'echoFrameMexRoot', 'vantageRoot'.
    """
    # -- Validate required paths ------------------------------------------------
    if not str(cfg.get("matlabRoot", "")).strip():
        raise RuntimeError(
            "matlabRoot not configured. Set MATLAB_ROOT environment variable "
            "or pass 'matlabRoot' in the config."
        )
    if not str(cfg.get("echoFrameMexRoot", "")).strip():
        raise RuntimeError(
            "echoFrameMexRoot not configured. Set ECHOFRAME_MEX_ROOT environment variable "
            "or pass 'echoFrameMexRoot' in the config."
        )
    if not str(cfg.get("vantageRoot", "")).strip():
        raise RuntimeError(
            "vantageRoot not configured. Set VERASONICS_VPF_ROOT environment variable "
            "or pass 'vantageRoot' in the config."
        )

    simulate_mode = int(cfg.get("simulateMode", 1))
    if simulate_mode not in (0, 1, 2):
        raise ValueError("simulateMode must be one of {0, 1, 2}.")

    rcv_data_mat_file = str(cfg.get("rcvDataMatFile", "")).strip()
    if rcv_data_mat_file:
        rcv_data_mat_file = str(Path(rcv_data_mat_file).expanduser())
        if not Path(rcv_data_mat_file).is_file():
            raise FileNotFoundError(
                f"rcvDataMatFile does not exist: {rcv_data_mat_file}"
            )
    if simulate_mode == 2 and not rcv_data_mat_file:
        raise ValueError(
            "simulateMode=2 requires rcvDataMatFile pointing to a MAT file "
            "containing RcvData."
        )
    print(
        f"[worker] Effective simulation mode: {simulate_mode}"
        + (f" (RcvData MAT: {rcv_data_mat_file})" if simulate_mode == 2 else ""),
        flush=True,
    )

    # -- 1. Configure MATLAB process environment ---------------------------------
    if sys.platform == "win32":
        matlab_lib = str(Path(cfg["matlabRoot"]) / "bin" / "win64")
        existing = os.environ.get("PATH", "")
        os.environ["PATH"] = matlab_lib + (";" + existing if existing else "")
    else:
        # These Linux-specific GUI settings mirror the wrapper script used to
        # launch MATLAB under distrobox/X11.
        # They keep MATLAB's Java/Qt windows rendering correctly under distrobox/X11.
        os.environ.setdefault("_JAVA_AWT_WM_NONREPARENTING", "1")
        os.environ.setdefault("WMNAME", "LG3D")
        os.environ.setdefault("QT_QPA_PLATFORM", "xcb")
        os.environ.setdefault("LC_ALL", "C")
        os.environ.setdefault("XMODIFIERS", "@im=none")

        matlab_lib = str(Path(cfg["matlabRoot"]) / "bin" / "glnxa64")
        existing = os.environ.get("LD_LIBRARY_PATH", "")
        os.environ["LD_LIBRARY_PATH"] = matlab_lib + (
            ":" + existing if existing else ""
        )

    # -- 2. Start MATLAB engine --------------------------------------------------
    import matlab.engine  # noqa: PLC0415  (import after env is set)

    startup_options = str(cfg.get("matlabStartupOptions", "")).strip()
    # On Linux, Verasonics activation can open a blank EULA window unless MATLAB
    # starts in software OpenGL mode from process launch.
    if sys.platform != "win32" and "-softwareopengl" not in startup_options.split():
        startup_options = (startup_options + " -softwareopengl").strip()

    if startup_options:
        print(
            f"[worker] Starting MATLAB engine with options: {startup_options}",
            flush=True,
        )
        eng = matlab.engine.start_matlab(startup_options)
    else:
        print("[worker] Starting MATLAB engine...", flush=True)
        eng = matlab.engine.start_matlab()
    print("[worker] Engine ready.", flush=True)

    # -- 3. Add EchoFrame and Effusive MATLAB paths ---------------------------
    ef_mex_root = Path(cfg["echoFrameMexRoot"])
    cf_root = Path(cfg["effusiveRoot"])

    # Effusive must be on path before effusive.vantage.activateVantage is called.
    eng.addpath(str(ef_mex_root), nargout=0)
    eng.addpath(str(cf_root), nargout=0)
    print("[worker] MATLAB paths set.", flush=True)

    vantageRoot = cfg["vantageRoot"]
    eng.eval(
        f"effusive.vantage.activateVantage('{vantageRoot}');",
        nargout=0,
    )

    # -- 4. Write initial parameters to base workspace ---------------------------
    eng.workspace["EFFUSIVE_PATH"] = str(cf_root)
    eng.workspace["probeName"] = cfg["probeName"]
    eng.workspace["transmitFrequency"] = float(cfg["transmitFrequency"])
    eng.workspace["storagePath"] = cfg["storagePath"]
    eng.workspace["sessionId"] = cfg["sessionId"]
    eng.workspace["bidsSubject"] = str(cfg.get("bidsSubject", "")).strip()
    eng.workspace["bidsSession"] = str(cfg.get("bidsSession", "")).strip()
    eng.workspace["bidsTask"] = str(cfg.get("bidsTask", "")).strip()
    eng.workspace["bidsAcq"] = str(cfg.get("bidsAcq", "")).strip()
    eng.workspace["bidsProc"] = str(cfg.get("bidsProc", "")).strip()
    eng.workspace["bidsRun"] = float(cfg.get("bidsRun", 1))
    eng.workspace["effusiveBidsMetaPath"] = str(bids.BIDS_META_SIDECAR_PATH)
    eng.workspace["voltage"] = float(cfg["voltage"])
    eng.workspace["transmitAperturePercentage"] = float(
        cfg["transmitAperturePercentage"]
    )
    eng.workspace["receiveAperturePercentage"] = float(cfg["receiveAperturePercentage"])
    eng.workspace["txrxFrameRate"] = float(cfg["txrxFrameRate"])
    eng.workspace["transmitPulseLength"] = float(cfg["transmitPulseLength"])
    eng.workspace["nTransmissions"] = float(cfg["nTransmissions"])
    eng.workspace["nRepeats"] = float(cfg["nRepeats"])
    eng.workspace["planewaveOpeningAngle"] = float(cfg["planewaveOpeningAngle"])
    eng.workspace["desiredEndDepthMm"] = float(cfg["desiredEndDepthMm"])
    eng.workspace["speedOfSound"] = float(cfg.get("speedOfSound", 1510.0))
    eng.workspace["beamformerType"] = str(cfg.get("beamformerType", "Fourier"))
    eng.workspace["dasFNumberAuto"] = bool(cfg.get("dasFNumberAuto", False))
    eng.workspace["dasFNumber"] = float(cfg.get("dasFNumber", 0.71))
    eng.workspace["tgcGain"] = float(cfg["tgcGain"])
    eng.workspace["tgcControlPoints"] = matlab.double(
        [float(value) for value in cfg["tgcControlPoints"]]
    )
    eng.workspace["simulateMode"] = simulate_mode
    eng.workspace["rcvDataMatFile"] = rcv_data_mat_file
    stack_motor_port = str(cfg.get("stackMotorPort", "")).strip()
    if stack_motor_port:
        eng.workspace["stackMotorPort"] = stack_motor_port
    eng.workspace["stackMotorMinMm"] = float(cfg["stackMotorMinMm"])
    eng.workspace["stackMotorMaxMm"] = float(cfg["stackMotorMaxMm"])
    shared_memory_name_meta = cfg.get("sharedMemoryNameMeta", SHARED_MEMORY_META_NAME)
    shared_memory_name_bmode = cfg.get(
        "sharedMemoryNameBmode", SHARED_MEMORY_BMODE_NAME
    )
    shared_memory_name_pdi = cfg.get("sharedMemoryNamePdi", SHARED_MEMORY_PDI_NAME)
    shared_memory_name_cmd = cfg.get("sharedMemoryNameCmd", SHARED_MEMORY_CMD_NAME)
    shared_memory_name_rf = cfg.get("sharedMemoryNameRf", SHARED_MEMORY_RF_NAME)
    shared_memory_name_stack = cfg.get(
        "sharedMemoryNameStack", SHARED_MEMORY_STACK_NAME
    )
    shared_memory_name_ack = cfg.get("sharedMemoryNameAck", SHARED_MEMORY_ACK_NAME)
    eng.workspace["sharedMemoryNameMeta"] = shared_memory_name_meta
    eng.workspace["sharedMemoryNameBmode"] = shared_memory_name_bmode
    eng.workspace["sharedMemoryNamePdi"] = shared_memory_name_pdi
    eng.workspace["sharedMemoryNameCmd"] = shared_memory_name_cmd
    eng.workspace["sharedMemoryNameRf"] = shared_memory_name_rf
    eng.workspace["sharedMemoryNameStack"] = shared_memory_name_stack
    eng.workspace["sharedMemoryNameAck"] = shared_memory_name_ack

    # -- 5. Call effusive.napari.setup (synchronous) -------------------------
    print("[worker] Running effusive.napari.setup...", flush=True)
    try:
        eng.eval("effusive.napari.setup();", nargout=0)
    except Exception as exc:
        print(f"[worker] effusive.napari.setup failed: {exc}", flush=True)
        eng.quit()
        sys.exit(1)

    # Read nz/nx from meta shared memory so we can log them (viewer reads them too).
    try:
        shared_memory_meta = shared_memory.SharedMemory(
            name=shared_memory_name_meta, create=False
        )
        shared_memory_meta_buffer = shared_memory_meta.buf
        if shared_memory_meta_buffer is None:
            raise RuntimeError("SharedMemory buffer is None")
        _, nz, nx, z0, z1, x0, x1, _, _ = struct.unpack_from(
            META_FORMAT, shared_memory_meta_buffer, 0
        )
        tracked_name = getattr(shared_memory_meta, "_name", shared_memory_meta.name)
        shared_memory_meta.close()
        # Python tracks create=False attachments too. Use the internal POSIX name
        # here (leading slash on Linux) so the tracker removes the exact entry it
        # registered, avoiding both a shutdown leak warning and the earlier KeyError
        # caused by unregistering the user-facing name.
        _safe_unregister_shared_memory(tracked_name)
        print(
            f"[worker] cf_setup done: nz={nz} nx={nx} "
            f"z=[{z0:.1f}, {z1:.1f}] mm  x=[{x0:.1f}, {x1:.1f}] mm",
            flush=True,
        )
    except Exception as exc:
        print(
            f"[worker] Could not read meta shared memory after cf_setup: {exc}",
            flush=True,
        )

    # -- 6. Run VSX (blocking until vsExit is set) ------------------------------
    # Log the MATLAB CWD and confirm the MAT file exists before calling VSX.
    try:
        cwd = eng.eval("pwd", nargout=1)
        fname = eng.eval("evalin('base','filename')", nargout=1)
        mat_path = Path(fname)
        if mat_path.suffix != ".mat":
            mat_path = mat_path.with_suffix(".mat")
        print(f"[worker] MATLAB CWD: {cwd}", flush=True)
        print(
            f"[worker] VSX filename: '{fname}' — MAT found: {mat_path.exists()}",
            flush=True,
        )
    except Exception as exc:
        print(f"[worker] Could not verify VSX MAT file: {exc}", flush=True)

    print("[worker] Starting VSX...", flush=True)
    try:
        eng.VSX(nargout=0)
    except Exception as exc:
        print(f"[worker] VSX ended: {exc}", flush=True)

    # -- 7. Quit -----------------------------------------------------------------
    eng.quit()
    print("[worker] Done.", flush=True)


if __name__ == "__main__":
    raw = sys.argv[1] if len(sys.argv) > 1 else "{}"
    try:
        user_cfg = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(f"[worker] Bad JSON config: {exc}", file=sys.stderr)
        sys.exit(1)

    # Build probe-aware defaults from the shipped config, then let user_cfg override.
    # Probe name is resolved first so probe-specific defaults (frequency, frame rate,
    # etc.) are correct for the probe being used.
    _probe_name = user_cfg.get("probeName")
    cfg = {**_defaults_from_config(_probe_name), **user_cfg}
    main(cfg)
