function Receive = configureReceive(transFrequencyMHz, ReceiveSpec)
% Configure the Verasonics receive structure array.
%
% Parameters
% ----------
% transFrequencyMHz : float
%     Transducer center frequency [MHz].
% ReceiveSpec : struct
%     EchoFrame receive specification.
%
% Returns
% -------
% Receive : struct
%     Verasonics receive structure array with one entry per acquisition.
arguments
    transFrequencyMHz (1,1) double
    ReceiveSpec (1,1) struct
end
    Receive = repmat( ...
        struct( ...
            startDepth=ReceiveSpec.lensOffset + ReceiveSpec.startDepthWavelengths, ...
            endDepth=ReceiveSpec.lensOffset + ReceiveSpec.endDepthWavelengths, ...
            TGC=1, ...
            bufnum=1, ...
            framenum=1, ...
            acqNum=1, ...
            sampleMode=ReceiveSpec.sampling_mode, ...
            demodFrequency=transFrequencyMHz, ...
            mode=0, ...
            callMediaFunc=0 ...
        ), ...
        1, ...
        ReceiveSpec.nRepeats * ReceiveSpec.nTransmissions * ReceiveSpec.nBuffers ...
    );

    for iFrame = 1:ReceiveSpec.nBuffers
        k = ReceiveSpec.nRepeats * ReceiveSpec.nTransmissions * (iFrame - 1);
        Receive(k+1).callMediaFunc = 1;
        for i = 1:ReceiveSpec.nTransmissions * ReceiveSpec.nRepeats
            Receive(i+k).Apod = ReceiveSpec.apodization;
            Receive(i+k).TGC = 1;
            Receive(i+k).framenum = iFrame;
            Receive(i+k).acqNum = i;
        end
    end
end
