function [BFStorageSpec, PDIStorageSpec, RFTimeTagStorageSpec, RFStorageSpec] = inactiveStorageSpecs(ReconSpec, PDISpec)
% Build placeholder storage specs for re-init calls without file creation.
%
% These specs keep EchoFrame re-init paths happy when saving is disabled, while avoiding
% folder creation and file allocation.
%
% Parameters
% ----------
% ReconSpec : struct
%     EchoFrame reconstruction specification; crop state and BF datatype are propagated
%     into the placeholder BF storage spec.
% PDISpec : struct
%     EchoFrame PDI specification; crop state is propagated into the placeholder PDI
%     storage spec.
%
% Returns
% -------
% BFStorageSpec : struct
%     Disabled BF storage spec compatible with `echoframe_mex` re-init.
% PDIStorageSpec : struct
%     Disabled PDI storage spec compatible with `echoframe_mex` re-init.
% RFTimeTagStorageSpec : struct
%     Disabled RF time-tag storage spec compatible with `echoframe_mex` re-init.
% RFStorageSpec : struct
%     Disabled raw RF storage spec compatible with `echoframe_mex` re-init.

    BFStorageSpec = struct( ...
        crop=logical(ReconSpec.cropBF), ...
        save=logical(false), ...
        maxNumberBuffers=int32(1), ...
        numberOfBuffers=int32(1), ...
        dataType=ReconSpec.bfDataType, ...
        filepath='', ...
        bufferSize=uint64(1), ...
        preallocateFullFile=logical(false) ...
    );

    PDIStorageSpec = struct( ...
        crop=logical(PDISpec.cropPDI), ...
        save=logical(false), ...
        maxNumberBuffers=int32(1), ...
        numberOfBuffers=int32(1), ...
        dataType='single', ...
        filepath='', ...
        bufferSize=uint64(1), ...
        preallocateFullFile=logical(false) ...
    );

    RFTimeTagStorageSpec = struct( ...
        crop=logical(false), ...
        save=logical(false), ...
        maxNumberBuffers=int32(1), ...
        numberOfBuffers=int32(1), ...
        dataType='double', ...
        filepath='', ...
        bufferSize=uint64(1), ...
        preallocateFullFile=logical(false) ...
    );

    RFStorageSpec = struct( ...
        crop=logical(false), ...
        save=logical(false), ...
        maxNumberBuffers=int32(1), ...
        numberOfBuffers=int32(1), ...
        dataType='int16', ...
        filepath='', ...
        bufferSize=uint64(1), ...
        preallocateFullFile=logical(false) ...
    );
end
