function [ProbeSpec, TransmitSpec, ReceiveSpec, ReconSpec, PDISpec] = validateEchoFrameStructs( ...
    ProbeSpec, TransmitSpec, ReceiveSpec, ReconSpec, PDISpec)
% Validate and cast EchoFrame structs expected by `echoframe_mex`.
%
% Parameters
% ----------
% ProbeSpec : struct
%     EchoFrame probe specification.
% TransmitSpec : struct
%     EchoFrame transmit specification.
% ReceiveSpec : struct
%     EchoFrame receive specification.
% ReconSpec : struct
%     EchoFrame reconstruction specification.
% PDISpec : struct
%     EchoFrame PDI specification.
%
% Returns
% -------
% ProbeSpec : struct
%     Validated and type-cast probe specification.
% TransmitSpec : struct
%     Validated and type-cast transmit specification.
% ReceiveSpec : struct
%     Validated and type-cast receive specification.
% ReconSpec : struct
%     Validated and type-cast reconstruction specification.
% PDISpec : struct
%     Validated and type-cast PDI specification.

    % Populate derived ReceiveSpec fields required by echoframe_mex.
    ReceiveSpec.FsIQ = ReceiveSpec.Fs / 2;
    ReceiveSpec.nElements = ProbeSpec.nElementsX;
    ReceiveSpec.Fc = ProbeSpec.Fc;
    ReceiveSpec.nBuffers = int32(2);

    expectedProbeSpecFields = {
        'pitchX', 'double'; ...
        'pitchY', 'double'; ...
        'Fc', 'single'; ...
        'nElementsX', 'int32'; ...
        'nElementsY', 'int32'; ...
        'element_position', 'single'; ...
    };

    expectedTransmitSpecFields = {
        'c0', 'double'; ...
        'type', 'char'; ...
        'steerX', 'single'; ...
        'steerY', 'single'; ...
        'apodization', 'double'; ...
        'transmitDelays', 'double'; ...
    };

    expectedReceiveSpecFields = {
        'nSamples', 'int32'; ...
        'nSamplesIQ', 'int32'; ...
        'nTransmissions', 'int32'; ...
        'nRepeats', 'int32'; ...
        'nChannels', 'int32'; ...
        'channel2ElementMap', 'int32'; ...
        'nElements', 'int32'; ...
        'isIQ', 'logical'; ...
        'Fs_base', 'single'; ...
        'Fs', 'single'; ...
        'FsIQ', 'single'; ...
        'Fc', 'single'; ...
        'rfDataType', 'char'; ...
        'nBuffers', 'int32'; ...
        'sampling_mode', 'char'; ...
        'samples_per_wavelength', 'int32'; ...
    };

    expectedReconSpecFields = {
        'method', 'char'; ...
        'bfDataType', 'char'; ...
        'getBF', 'logical'; ...
        'getPDI', 'logical'; ...
        'nDims', 'int32'; ...
        'nz', 'int32'; ...
        'nx', 'int32'; ...
        'filterFrequencies', 'logical'; ...
        'cropBF', 'logical'; ...
        'croppingROI', 'int32'; ...
        'nBuffers', 'int32'; ...
        'extra_voxels_z', 'int32'; ...
        'extra_voxels_x', 'int32'; ...
        'c0', 'single'; ...
        'tgcVector', 'single'; ...
        'delayIndices', 'int32'; ...
        'interpolationWeights', 'single'; ...
        'frequencyAxis', 'single'; ...
        'planewaveDelays', 'single'; ...
        'xAxis', 'double'; ...
        'zAxis', 'double'; ...
    };

    expectedPDISpecFields = {
        'ensembleSize', 'int32'; ...
        'threshold', 'single'; ...
        'shiftSize', 'int32'; ...
        'cropPDI', 'logical'; ...
        'svdMethod', 'char'; ...
    };

    ProbeSpec = validateAndCast(ProbeSpec, expectedProbeSpecFields, 'ProbeSpec');
    TransmitSpec = validateAndCast( ...
        TransmitSpec, expectedTransmitSpecFields, 'TransmitSpec' ...
    );
    ReceiveSpec = validateAndCast( ...
        ReceiveSpec, expectedReceiveSpecFields, 'ReceiveSpec' ...
    );

    % Support old ReconSpec format where `nx` stored both dimensions.
    nxSize = size(ReconSpec.nx);
    if nxSize(2) > 1
        ReconSpec.nz = ReconSpec.nx(1);
        ReconSpec.nx = ReconSpec.nx(2);
    end
    ReconSpec = validateAndCast(ReconSpec, expectedReconSpecFields, 'ReconSpec');
    PDISpec = validateAndCast(PDISpec, expectedPDISpecFields, 'PDISpec');
end


function structOut = validateAndCast(structIn, expectedFields, structName)
% Validate fields in a struct and cast each one to the expected type.

    for iField = 1:size(expectedFields, 1)
        fieldName = expectedFields{iField, 1};
        expectedType = expectedFields{iField, 2};

        if ~isfield(structIn, fieldName)
            error('Field "%s" is missing from %s.', fieldName, structName);
        end

        fieldValue = structIn.(fieldName);
        if isempty(fieldValue)
            error('Field "%s" in %s is not initialized.', fieldName, structName);
        end

        if ~isa(fieldValue, expectedType)
            structIn.(fieldName) = castField(fieldValue, expectedType);
        end
    end
    structOut = structIn;
end


function valueOut = castField(valueIn, expectedType)
% Cast a value to the requested MATLAB type name.

    switch expectedType
        case 'int32'
            valueOut = int32(valueIn);
        case 'single'
            valueOut = single(valueIn);
        case 'logical'
            valueOut = logical(valueIn);
        case 'char'
            valueOut = char(valueIn);
        otherwise
            error('Unknown cast target: %s.', expectedType);
    end
end
